name: Deploy to Hostinger

on:
  push:
    branches:
      - develop # O la rama que uses en tu repositorio, como master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.3' # Coincide exactamente con tu entorno local

      - name: Instalar dependencias y compilar
        run: |
          flutter pub get
          flutter build web --dart-define=API_URL=${{ secrets.API_URL }}

      - name: Desplegar a Hostinger vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: ./
